version: '3.7'
services:
  db:
    image: postgres:14.0
    networks:
      - bookmarket
    env_file: .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    image: allyotov/bookmarket_backend:1.0.1
    networks:
      - bookmarket
    env_file: .env
    volumes:
      - ./backend_data:/data

  bot:
    image: allyotov/bookmarket_bot:1.1.0
    networks:
      - bookmarket
    env_file: .env

networks:
  bookmarket: