version: '3.7'
services:
  db:
    image: postgres:14.0
    networks:
      - bookmarket
    env_file: .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    image: allyotov/bookmarket_backend:1.0.0
    networks:
      - bookmarket
    env_file: .env
    volumes:
      - ./backend_data:/data
    ports:
      - 5000:5000

  bot:
    image: allyotov/bookmarket_bot:1.0.0
    networks:
      - bookmarket
    env_file: .env
    ports:
      - 5434:5434

networks:
  bookmarket: